import { themeLibrary, ThemeName } from '@/lib/designSystem'

const TERMS_THEME: ThemeName = 'twilight'

const TERMS_TEXT = String.raw`
Terms & Conditions and User Agreement for transacting at and/or dealing with the Website https://discoverwhoami.com/ at Divine Wisdom

Recitals
This document is an electronic record in terms of Information Technology Act, 2000 and rules there under as applicable as amended from time to time. This electronic record is generated by a computer system and does not require any physical or digital signa
This document is published in accordance with the provisions of Rule 3 (1)(a) of the Information Technology (Intermediary Guidelines and Digital Media Ethics Code) Rules, 2021 (“IT Intermediary Rules”) and the Information Technology (Reasonable Security Practices and Procedures and Sensitive Personal Data or Information) Rules, 2011 that require publishing the rules and regulations, privacy policy and user agreement for access or usage of “The Who Am I Course” at https://discoverwhoami.com/ (“Website”).
The Website is owned and operated by Divine Wisdom, a sole proprietorship of Mrs. Santosh Sachdeva, having its office at Sangam Bhavan. Brahma Marg, Colaba, Mumbai, hereinafter referred to as “Divine Wisdom” (which expression shall, unless it be repugnant to the context or meaning thereof, include her legal heirs, successors and assigns).
Subject to the terms and conditions of this Agreement (as defined hereinafter), Divine Wisdom shall make available through the Website access to “The Who Am I Course” Course  delivered by Mrs. Santosh Sachdeva  (“Instructor”) designed to Divine Wisdom (“Digital Content”) in consideration of a subscription fee as reflected on the Website while availing the content as may be amended by Divine Wisdom at its sole discretion from time to time (“Subscription Fees”) on the terms and conditions set out herein (“Services”). The Digital Content so made available through the Website is owned by the Instructor and Divine Wisdom. It is expressly clarified that Divine Wisdom may render certain specific Services without any charges for a specific time period as may be deemed fit by Mrs. Santosh Sachdeva and which shall be notified on the Website from time to time. While Divine Wisdom shall make its best endeavours to filter the Digital Content uploaded by and her team Divine Wisdom and comments, images and data uploaded by the Users to the best extent possible, Divine Wisdom provides no warranties for, and accepts no liability therein.It is expressly stated that any view and/or opinion offered by the Instructor in the Digital Content is such Instructor’s own view and/or opinion based on her personal experience in the wellness space and should not be construed as medical advice pertaining to physical and/or mental health. By accessing the Digital Content, the User acknowledges that the results arising from the practise of the techniques demonstrated in the Digital Content vary from person to person and the User is advised to immediately discontinue its practise if he/she/they experience any adverse reactions thereto, and that Divine Wisdom shall undertake no liability, whether financial or otherwise, for any use of misuse of the information, guidance, and directions comprising the Digital Content.
Further, it is expressly stated that the User shall be solely responsible and liable for the comments, images and data uploaded by the User at all times whether financially or otherwise.

Use of this Website is regulated by terms and conditions provided herein. By clicking on the “I ACCEPT” button, you are consenting to be bound by these terms and conditions and Privacy Policy (as defined hereinafter) of Divine Wisdom. Please ensure that you read and understand all these user terms before you use the Website. If you do not accept any of the user terms, then please do not use the Website or avail any of the Services being provided on the Website. Your agreement to these user terms shall operate as a binding agreement between you and Divine Wisdom in respect of the use of the Services and the Website. Your access, visit, dealing, transacting and/or otherwise using this Website shall be treated as your unconditional acceptance of these terms in entirety and the same shall be deemed to mean that you have accepted these terms fully and you have gone through and understood these terms completely and these terms shall be treated as a legally binding and enforceable Agreement between Divine Wisdom and you (“Acceptance”). If you do not agree with any or all of these terms, then you should stop dealing with and/or not initiate or undertake any transaction on this Website.
The information and Services offered on this Website should not be considered as a substitute for professional advice including medical and health advice from a certified medical professional. The User’s use of the Website and/or Services is subject to the additional disclaimers and caveats that may appear throughout the Divine Wisdom assumes no responsibility for any consequence relating directly and/or indirectly to any action and/or inaction that the User takes based on the information, Services and other materials on this Website. While Divine Wisdom strives to keep the information relating to the various Services offered on this Website accurate, complete and up-to-date, Divine Wisdom cannot guarantee, and will not be responsible for any liabilities, damage and/or loss related to, the accuracy, completeness or timeliness of the information.
Divine Wisdom may change, suspend and/or discontinue the Services at any time, including the availability of any feature, database and Digital Content on the Divine Wisdom may also impose limits on certain features and Services and/or restrict the User’s access to parts and/or all of the Services without notice and/or liability to the Users.
All kind of correspondence should be addressed to Divine Wisdom ’s office address as given above.
II TERMS AND CONDITIONS

1. Definitions

The words and phrases used in these terms are defined as under unless repugnant to the context or meaning thereof:

“Acceptance” shall have the meaning ascribed to it in Recital I (5).

“Agreement” shall mean this agreement between Divine Wisdom and the User with terms and conditions as provided herein and includes the Privacy Policy and all schedules, appendices and references mentioned herein with all such amendments as effected by Divine Wisdom from time to time.

“Digital Content” shall have the meaning ascribed to it in Recital I (4).

“Intellectual Property Rights” shall have the meaning ascribed to it in Clause 4.1(a).

“Marks” shall have the meaning ascribed to it in Clause 4.1(e).

“Privacy Policy” shall mean the privacy policy as displayed on the Website, at Divine Wisdom as may be amended from time to time and forming an integral part of the Agreement.

“Subscription Fee” shall have the meaning ascribed to it in Recital I (4).

“Services” shall have the meaning ascribed to it in Recital I (4).

“Instructor” shall have the meaning ascribed to it in Recital I (4).

“Third Party Content” shall have the meaning ascribed to it in Clause 5.1.

“User” shall mean any person that visits, uses, deals with and/or transacts on the Website in any way. Any references herein to ‘you’ and ‘your’ shall mean the User.

“User Content” shall have the meaning ascribed to it in Clause 5.3

“Website” shall have the meaning ascribed to it in Recital I (3).

“Web Links” shall have the meaning ascribed to it in Clause 12.

In this Agreement, ‘Divine Wisdom’ and the ‘User’ have been collectively referred to as “Parties” and individually as “Party”.

2. Eligibility 

2.1 The User hereby represents and warrants that the User is atleast Eighteen (18) years of age and the User’s visit, access, dealing and/or transaction at the Website and/or availing any Services shall be treated as the User’s representation that the User is competent to enter into legal contracts under applicable law including the Indian Contract Act, 1872.

2.2 If the User is availing of the Services, the User further warrants that the User has legal authority to enter into legally binding agreements for the sam The User agrees to be financially or otherwise responsible for all of the User’s use of the Services and access of the Website (as well as for use of the User’s account by others). The User also warrants that all information supplied by the User in availing the Services and accessing the Website, including without limitation the User’s Content, the User’s name, email address, street address, telephone number, mobile number, credit/debit card number and other payment details and any other information including sensitive personal data and information is correct and accurate. Failure to provide accurate information may subject the User to civil and criminal penalties including termination of account from the Website either temporarily or permanently or removal of inaccurate or false information. This Agreement and/or any of the provision is void where prohibited by law, and the right to access the Website is revoked in such jurisdictions. The User acknowledges and agrees that Divine Wisdom shall have the right and is obligated under applicable laws to retain the information for the purpose of rendering the Services and/or for a period of atleast 180 (one hundred eighty) days after cancellation or withdrawal of registration on the Website and/or till such time as may be required under law and/or by an order of any relevant authority.

2.3 The User acknowledges and agrees that Divine Wisdom has the right to terminate your access and usage rights to the Website and Services including removal of non-compliant information in the case of your non-compliance with any provision of this Agreement.

2.4 The User acknowledges and agrees that any direct interaction between the Users connected through the Website or between Users and Instructor shall be governed by terms and conditions agreed between them, and Divine Wisdom is not a party to such arrangement and accordingly shall not be responsible and/or liable whether financially or otherwise in regard to such inter-connection. The User agrees that Divine Wisdom is not liable, financially or otherwise, for any consequences suffered by actions including, but not limited to, the sharing of personal information during such interactions.

3. Amendment of Terms

Divine Wisdom is entitled to amend these terms anytime without any prior intimation to anybody and simply by way of notification on the Website. Such a notification shall serve as information to the User in compliance with the IT Intermediary Rules. The User shall be responsible for reviewing and becoming familiar with any such modifications/amendments from time to time and shall be bound to this Agreement as amended by Divine Wisdom from time to time. Use of the Services by the User following such notification constitutes the User’s acceptance of the terms and conditions of this Agreement as modified.

4. Intellectual Property

4.1 Website – Digital Content

(a) The User acknowledges and agrees that Divine Wisdom retains all right, title, ownership and interest in and to the Website, all data and information, content, articles, material, text, literature, images, illustrations, photographs, videos, clippings, graphics, scripts, page headers, sounds, music, interactive features, the selection and arrangement of elements, the compilation, layout, design, software, domain name, business process, procedures, in any form whatsoever including but not limited to, print, writing, oral, electronic, digital/IT enabled, in machine readable and/or in any other form, and all patent rights, copyright rights, trademark rights, service mark rights, trade secret rights and other intellectual property rights therein recognized anywhere in the world including the Digital Content (“Intellectual Property”), other than ownership rights in the Third Party Content or User Content. All use of such rights, including the Intellectual Property, in any manner, medium or mode shall perpetually and throughout the world legally vest in the Instructor and Divine Wisdom at all times.

(b) Payment of the Subscription Fee by the User to Divine Wisdom for a particular Service merely grants the User a non-exclusive, temporary, revocable and conditional license to access and avail the Service for a given period of time as set out on the Website.

(c) All Intellectual Property of Divine Wisdom is a valuable asset of Divine Wisdom and the User agrees to protect, preserve and maintain confidentiality of the sam The User acknowledges that any unauthorized dissemination of the Intellectual Property of Divine Wisdom would destroy or diminish its value and cause irreparable harm and loss to Divine Wisdom, and that monetary damages will be inadequate to compensate Divine Wisdom for any breach thereof. The User, therefore, agrees that Divine Wisdom shall, in addition to its rights in law and equity including to its right to claim damages, have the right to seek immediate injunctive relief and specific performance to enforce the obligations contained herein.

(d) The Website is protected by copyright as a collective work and/or compilation, pursuant to the Copyright Act, 1957, international conventions, and other worldwide copyright laws. The User is not authorized to reproduce, republish, distribute, transmit, modify, edit, sell, transfer, license, translate, communicate, publish, use or exploit the Website and/or its Digital Content and/or any information in any manner whatsoever or create derivative works based on it, in whole or in part, without Divine Wisdom ’s express written authorization, which Divine Wisdom is under no obligation to grant

(e)  Any logo, trademark, brand name, service mark, trade name, slogan, and other indicia, whether registered or not (“Marks”) that appear on or in connection with the Website and/or its Digital Content, is the intellectual property of Divine Wisdom. Divine Wisdom expressly reserves all rights therein and the User agrees not to display, use or exploit the same in any manner whatsoever. Nothing contained in this Website should be construed as granting, by implication, estoppels, or otherwise, any license or right in and to the Marks.

(f) The User agrees that, according to standard practice, if a User uses any information available on the Website for any research that results in an article, presentation, and/or other publication, the User lists Divine Wisdom as a resource in User’s bibliography and the User shall take prior permission and (i) give proper credit and ensure that Divine Wisdom ’s copyright notice appears on all copies; (ii) ensure that no documents or graphics, including logos, available from the Website are modified in any way.

(g) The User’s misuse of the Website and/or its Digital Content and/or its Marks, is strictly prohib The User is advised that Divine Wisdom will aggressively enforce its right in the Intellectual Property and the contents of the Website to the fullest extent permissible by law, including by seeking appropriate remedies including criminal sanctions solely at the User’s risk as to costs and consequences thereof. Divine Wisdom has all the rights to disable or prohibit access to the Users who do not abide by these terms and involve themselves in the infringement of the Intellectual Property. A failure or refusal to enforce these rights by Divine Wisdom in specific instances is not an indication of the waiver of such rights

(h)  All the information and Digital Content disclosed on the Website except the Third-Party Content and User Content is proprietary in nature and solely belongs to Divine Wisdom and its respective licensors and shall not be used and/or copied and/or tampered with in any manner (as the case may be).

(i) The Users hereby further acknowledge that any views and/or opinions offered by any Instructor on the Website through any courses, webinars, workshops, etc, whether pre-recorded or broadcast live, is the Instructor’s own view and/or opinion, based on personal experiences. Such views / opinions are not to be construed as medical advice, and Divine Wisdom shall bear no liability (financial or otherwise) with respect to any use or misuse of the same.

 5 Third Party Content and User Content

5.1 The User hereby acknowledges that there may be publishers, advertisement agencies, other corporates, persons and legal entities who may upload third party trademarks, logos, photographs, images, content, products and/or services for promotions and other intellectual property rights on the Website (“Third Party Content”). Divine Wisdom shall not be responsible and/or liable for any such Third Party Content.

5.2 The User hereby agrees and acknowledges that the Third-Party Content are the properties of the respective third parties and the same may be protected by applicable copyright, trademark or other intellectual property laws and treaties and each such third party expressly reserves all the rights to such intellectual property. Divine Wisdom does not solicit and/or recommend such Third Party Content to be used by the Users for making any decision by the Users.

5.3 The Users shall be uploading comments, images, data and other information including sensitive personal data and information for registration purpose and/or for payment of Subscription Fees which is either owned or licensed to such Users on the Website as part of the Services rendered through the Website (“User Content”). The User hereby represents and warrants that the User Content is owned by such User or the User has the license to use such User Content and upload the same on the Website. Further, User uploading such User Content hereby acknowledges that the same is being done at the sole discretion and risk of the User and if such User Content is collected by a third party using the Website which is misused or results in unsolicited messages from such third parties, then such actions would be beyond the control of Divine Wisdom and Divine Wisdom accepts no responsibility or liability whatsoever for such actions.

5.4 Divine Wisdom shall have the right to scan, filter, block and verify the Third Party Content and User Content for reasons including, but not limited to, the threat of virus, bugs and other such software malware and retains the right to remove any Third Party Content and/or User Content at its sole discretion.

5.5 The User is hereby informed that you may not host, display, upload, modify, publish, transmit, store, update or share any information that:

(a) Defamtory to another person and to which the User does not have any right;is d
(b) efamatory, obscene, pornographic, paedophilic, invasive of another’s privacy, including bodily privacy, insulting or harassing on the basis of gender, libellous, racially or ethnically objectionable, relating or encouraging money laundering or gambling, or otherwise inconsistent with or contrary to the laws in force;
(c) is harmful to child;
(d) infringes any patent, trademark, copyright or other proprietary rights;
(e) violates any law for the time being in force;
(f) deceives or misleads the addressee about the origin of the message or knowingly and intentionally communicates any information which is patently false or misleading in nature but may reasonably be perceived as a fact;
(g) impersonates another person;
(h) threatens the unity, integrity, defence, security or sovereignty of India, friendly relations with foreign States, or public order, or causes incitement to the commission of any cognisable offence or prevents investigation of any offence or is insulting other nation;
(i) contains software virus or any other computer code, file or program designed to interrupt, destroy or limit the functionality of any computer resource;
(g) is patently false and untrue, and is written or published in any form, with the intent to mislead or harass a person, entity or agency for financial gain or to cause any injury to any person.

5.6 The User acknowledges and accepts that Divine Wisdom has the right to disable access to, or remove any content that is in violation of Clause 5.5 above, and has the right to terminate the access or usage rights for Users dealing in such content. Such content may be retained by Divine Wisdom for compliance with applicable laws including the IT Intermediary Rules in accordance with applicable laws.

5.7 Certain elements of the Website may contain material submitted by other Users and/or third pa Divine Wisdom disclaims its responsibility for the content, accuracy, conformity to applicable laws of such material including advertising material forming part of the Website. Responsibility for ensuring that material submitted for inclusion on the Website complies with applicable laws is exclusively on the advertisers and third parties and Divine Wisdom will not be responsible for any claim, error, omission and/or inaccuracy arising out of or in relation to such material. Divine Wisdom reserves the right to omit, suspend and/or change the position of any material submitted for insertion on the Website. Acceptance of advertisements on the Website shall be subject to Divine Wisdom ’s terms and conditions applicable to advertisements.

5.8 The User shall abide by all copyright notices, intellectual property rights, information and restrictions contained in any content accessed through the Services and the Website.

5.9 Divine Wisdom shall have the right to not host, store or publish any unlawful information and/or forthwith remove the same which is prohibited under any applicable laws in relation to sovereignty and integrity of India, security of India, friendly relations with foreign states, public order, decency, morality, contempt of court, defamation, incitement to any of the aforesaid offences, or any other information which is prohibited under any law. Divine Wisdom shall also remove any of the aforementioned information on receipt of any order of Court of competent jurisdiction or being notified by appropriate government or its agencies.

Further, Divine Wisdom shall provide information in its possession of any User and/or Instructor and/or third parties if required pursuant to any written order from any government agency which clearly sets out the purpose of seeking such information in accordance with applicable laws and IT Intermediary Rules.

Divine Wisdom shall also report cyber security incidents and share related information in accordance with the policies and procedures as set out under applicable laws.

6. Registration Data

6.1 The User shall be entitled to use the Website for any purpose set out therein after getting registered on the Website and after furnishing all relevant information relating to the User as sought on the The User shall be solely responsible for maintaining and preserving the confidentiality of your User ID and password.

6.2 The User shall be solely responsible for the accuracy and correctness of all such detail/information given by the User during registration. Divine Wisdom may at its sole discretion verify those details, if it deems If Divine Wisdom has reason to doubt the correctness and/or authenticity of any detail/information furnished by the User or in case any information furnished by the User is found incorrect, false or misleading then Divine Wisdom shall be entitled to cancel or suspend the registration of the User permanently or for such period as Divine Wisdom deems fit.

6.3 The User hereby grants Divine Wisdom the right to use the information the User supplies to Divine Wisdom for the purpose of the Services and conducting background and credit check wherever deemed necessary. The User hereby agrees to grant Divine Wisdom a non-exclusive, fully paid and royalty-free, transferable, sub-licensable, worldwide license and right to exercise the copyright, publicity, and database rights the User has in this information, in any media now or in future known, with respect to the User’s informa

6.4 The User confirms that Divine Wisdom shall not be responsible for:

(a)  Any deficiency in Service for reasons which are attributable to the User.
(b)  Any loss and/or damage to the User due to incorrect, incomplete and/or false information furnished by the User.
(c)  Any technical or non-technical payment related snags which the User may face through the use of the third-party payment gateways as provided by Divine Wisdom on the Website.

6.5 The User shall be liable to be prosecuted and/or punished under applicable laws for furnishing false, incorrect, incomplete and/or misleading information to Divine Wisdom.

6.6 The User accepts and acknowledges that Divine Wisdom shall retain the information provided by you at the time of registration even after your access to the Services has been cancelled or withdrawn, in compliance with the IT Intermediary Rules and/or any order of the relevant authority and/or as may be required under any applicable laws.

7. Representation, Warranties, Acknowledgement, Covenants, Undertakings And Obligations

7.1 The User represents and warrants that the User has the legal capacity and authority to enter into this Agreement, register on the Website and that the User is the owner and/or is authorized to share the information the User gives on the The User confirms that the information is correct, complete, accurate, not misleading, does not violate any statutory enactment, notification, order, circular, policy, rules and regulations, is not injurious to any person and/or property.

7.2 The User acknowledges and understands that Divine Wisdom does not have any control on accuracy of information/detail submitted by anybody on the Website and therefore agrees that Divine Wisdom shall not be responsible for any liabilities, loss, damage, cost, expenses, etc. due to inaccuracy of any detail/information submitted by the User or anybody else on the

7.3 The User represents, warrants and covenants that information submitted by the User:

(a) is correct, complete, relevant and accurate;
(b) is not fraudulent;
(c) does not and shall not infringe any third party’s intellectual property, trade secret and/or other proprietary rights and/or rights of publicity and/or privacy;
(d) shall not be defamatory, libellous, unlawfully threatening and/or unlawfully harassing;
(e) shall not be indecent, obscene and/or contain pornography and/or contain any thing which is prohibited under any prevailing laws, rules & regulations, order of any court, forum, statutory authority;
(f) shall not be seditious, offensive, abusive, liable to incite racial and/or religious hatred, discriminatory, menacing, scandalous, inflammatory, blasphemous, in breach of confidence, in breach of privacy and/or which may cause annoyance and/or inconvenience;
(g) does not constitute and/or encourage conduct that would be considered a criminal offence, give rise to civil liability, and/or otherwise be contrary to the law;
(h) shall not be or include material that is technically harmful (including, without limitation, computer viruses, logic bombs, Trojan horses, worms, harmful components, corrupted data or other malicious software or harmful data) or other computer programming routines that may damage, detrimentally interfere with, diminish value of, surreptitiously intercept or expropriate any system, data or personal information;
(i) shall not create liability and/or claims for Divine Wisdom;
(j) shall not be in the nature of political campaigning, commercial solicitation, chain letters, mass mailings and/or any form of ‘spam’;
(k) shall not be illegal in any other way.

7.4 Divine Wisdom reserves the right to remove and/or edit any detail/information that Divine Wisdom in its sole discretion deems appro The User confirms that you shall abide by all notices and all the terms and conditions (as updated from time to time) contained and mentioned herein.

7.5 The User undertakes and confirms that the User shall not use the Website, Services and/or materials therein for any purpose that is unlawful and/or prohibited by the terms of this Agreement and/or under any applicable laws, rulings, notifications, orders of any court or statutory autho

7.6 The User shall not use the Website, Services and/or materials therein in any manner which could damage, disable, overburden and/or impair the Website and/or any Services therein and/or the network(s) connected to the Website and interfere with another User’s use and enjoyment of the Website and/or Services ther

7.7 The User shall not attempt to gain unauthorized access to any Service on the Website, other users’ account(s), computer systems and/or networks connected to the Website through hacking, password mining and/or any other mean The User shall not attempt to obtain any materials or information through any means not intentionally made available to the User through the Website.

7.8 Divine Wisdom shall not be responsible and/or liable for any claims, losses and/or damages accruing to or affecting the User, as a result of: (i) engaging with any third party, including advertisers; and/or (ii) any defects/deficiencies in the services provided by any third party, including advertisers; and/or (iii) any claims/actions (including consumer claims) arising thereto; and/or (iv) any violation by the Users of the rights of third party’s and other Users, including without limitation, infringement of copyright, trademark, service mark, patent, trade secret, privacy or other intellectual property or proprietary right or misappropriation of any property  Advertisement/advice (if any) received via the Website should not be relied upon for personal, legal and/or financial decisions and the User should consult an appropriate professional for specific advice tailored to your situation.

7.9 The User agrees that Divine Wisdom is not liable, financially or otherwise, for any consequences suffered by actions including, but not limited to, the sharing of personal data during the User’s interactions with third parties or other Users of the Website.

7.10 The User shall be solely responsible for obtaining and maintaining any equipment or ancillary services needed to connect to, access the Website or otherwise use the Services, including, without limitation, modems, hardware, software, and long distance or local telephone The User shall be responsible for ensuring that such equipment or ancillary services are compatible with the Services.

8. Payment Terms and Refund Terms

8.1 The User shall be entitled to use User’s valid credit/debit cards, online/net banking facility, tele banking facility to make payment for the Subscription Fee for the The User shall be bound to use User’s own credit/debit cards, online banking accounts to make any payment. The User undertakes and confirms that you would furnish correct, complete and accurate detail of credit/debit cards, online banking accounts and shall be solely responsible for any cost, expense, loss and/or damage which the User may suffer due to furnishing of wrong detail/information relating to your credit/debit cards or online banking accounts.

8.2 Divine Wisdom confirms that the details provided by the User in this regard shall be kept confidential and shall not be disclosed to any third-party except to the extent required under the rules of any stock exchange and/or by applicable laws, regulations and/or processes of any government authority and/or in connection with any judicial process regarding any legal action, suit and/or proceeding arising out of and/or relating to this Agreement and/or relating to provision of Services by Divine Wisdom . The details provided by the User shall be retained after your access to Services has been cancelled or withdrawn, in compliance with the IT Intermediary Rules and/or any applicable laws.

8.3 The User here represents and acknowledges that all payments made by the User to Divine Wisdom shall be strictly on a non-refundable basis and the Subscription Fees paid by a User towards the Services are non – refundable and non-transferable subject to Clause 8.4.

8.4 Divine Wisdom may remove any Digital Content and/or Third Party Content and/or User Content, if the same is not in compliance with applicable laws. In the event, the Digital Content has been subscribed by any User and the same has been removed due to its non-adherence with standards as set out under applicable laws, the User shall be refunded the pro rata proportion of the Subscription Fees, if only a part of the Digital Content has been removed and in the event, the entire Digital Content is not available for the User, entire Subscription Fees shall be refunded to the User within a period of 10 (ten) days of removal of the Digital Content or any part thereof.

8.5 Divine Wisdom shall take all reasonable precautions to protect the information provided by the User. However, it is expressly provided and accepted by the User that Divine Wisdom shall not be responsible in any manner whatsoever for any third party action which results in the information provided by the User being exposed, misused and/or fraudulently misused in any manner whatsoever by such third- party.

8.6 The User acknowledges that the User is accessing the Digital Content at their free will and Divine Wisdom does not own the User Content and the Third Party Content.

9. Force Majeure

Divine Wisdom shall not be liable for any failure and/or delay on its part in performing any of its obligation under this Agreement and/or for any liabilities, loss, damage, costs, charges and expenses incurred and/or suffered by the User by reason thereof if such failure and/or delay shall be result of or arising out of Force Majeure Event set out herein. Divine Wisdom shall inform about occurrence of Force Majeure Event through notice on the Website to the best extent possible. During the continuation of Force Majeure Event, the obligations of Divine Wisdom under the Agreement shall stand suspended till ceasing of the Force Majeure Event. Divine Wisdom shall make its best endeavours to resolve any issues in regard to Force Majeure Event at the earliest and keep the Users updated on the same through notification on the Website.

A “Force Majeure Event” means any event due to any cause beyond the reasonable control of Divine Wisdom , including, without limitation, unavailability of any communication system, sabotage, fire, flood, earthquake, explosion, acts of God, civil commotion, strikes, lockout, and/or industrial action of any kind, breakdown of its facilities, riots, insurrection, terrorist attack, hostilities whether war be declared or not, acts of government, governmental orders or restrictions, pandemics, epidemics, breakdown and/or irregularities in networks, bugs, viruses, breakdown of software, hacking of the Website and/or contents provided for availing the Services under the Website.

10. Warranty Disclaimer

10.1 The User acknowledges that Divine Wisdom has no control over and no duty to take any action regarding (i) the User gaining access to the Website and/or its content and/or Services; (ii) what effect the Website and/or its content and/or Services may have on the User and/or any third-party; (iii) how the User may interpret or use the Website and/or its content and/or Services; (iv) what actions the User may take as a result of having been exposed to the Website and/or its content and/or Service The User assumes full responsibility for the actions taken before, during, and after accessing the Website, and their consequences, and releases Divine Wisdom from all liability whether financial or otherwise for the User having accessed the Website and/or its content and/or Services.

10.2 Divine Wisdom provides access to the Website on an ‘as is’ and ‘as available’ basis. Neither does Divine Wisdom nor do any third parties (except as expressly stated by such third party), provide any warranty or guarantee, express or implied, as to the accuracy, fitness, merchantability, availability, quality, performance, completeness or suitability of the Website and/or its content and/or Services, for any specific purpos Divine Wisdom expressly disclaims any warranty as to any specific outcomes from the use of the Services. The User acknowledges that the Website and/or its content and/or Services may contain inaccuracies or errors and Divine Wisdom expressly excludes liability whether financial or otherwise for any such inaccuracies or errors to the fullest extent permitted by law.

10.3 Although Divine Wisdom has taken adequate safeguards, Divine Wisdom makes no guarantee of confidentiality and/or privacy of any User communication or information transmitted on the Website and/or for the Services and/or on any website linked to the The User uses this Website and/or Services and/or on any website linked to the Website at his/her/its own risk.

10.4 The Website and/or its content and/or Services may contain views, opinions and recommendations of Users of the Website and/or Services, Third Party Content, User Content, advertisers, third-party information providers and organization The Website does not warrant, represent and/or endorse the correctness, authenticity, accuracy, completeness, reliability or validity of any such information displayed, uploaded, distributed, posted, emailed, transmitted or otherwise contributed through the Website by anybody other than Divine Wisdom. Divine Wisdom assumes no responsibility to keep the content current, complete, up-to-date, valid, or accurate. Divine Wisdom shall not be responsible in any manner whatsoever whether financially or otherwise for any errors and omissions in the materials and/or content even if such errors or omissions are due to negligence. The User acknowledges that any reliance upon any such view, opinion, advice, recommendation or information, User Content, Third Party Content shall be at the User’s sole risk.

10.5 The Digital Content provided on the Website is based on the Instructors personal experiences, and the results arising therefrom vary from person to person. The User acknowledges and agrees that the use of such information and guidance is at the User’s sole discretion, and exempts Divine Wisdom from all liability, financial or otherwise, that may arise therefrom. We provide no warranty for any specific outcomes the User may desire from the use of any information or guidance obtained through the Website and its Instructor. Divine Wisdom takes no responsibility and disclaims all liability for misuse of the Digital Content accessed through the Website and its Instructor.

10.6 Divine Wisdom does not warrant the accuracy, reliability, credibility or completeness of the Website and/or its content and/or its Ser Divine Wisdom makes no warranty that its Website and/or its content are appropriate or available for use in all locations. Those who access the Website and/or its content from territories other than India shall do so at their own risk and hereby unconditionally represent and undertake that they are responsible for full compliance with their local laws and the applicable laws of India.

10.7 The User shall be solely responsible to maintain the confidentiality and security of his/her/its account, User ID, password, login credentials and Divine Wisdom shall not be responsible for any losses arising out of the unauthorized access and/or use of the User’s account as a result of the User not following the terms and conditions stated herein.

10.8 Divine Wisdom shall be under no liability whether financial or otherwise of any nature whatsoever in respect of any loss, damage, claim or fraud suffered directly or indirectly by the User as a result of the User viewing, accessing, visiting and/or otherwise using the Website.

10.9 The User expressly understands and agrees that Divine Wisdom and the Instructor, shall not be liable to the User for any direct, indirect, incidental, special, consequential, punitive or exemplary damages, including, but not limited to, damages for loss of profits, goodwill, use, data, or other intangible losses resulting from:

(a) the User’s use or inability to use the Website;
(b) the User’s inability to access Digital Content which has been removed, or to which access has been disabled by Divine Wisdom for any reasons whatsoever, including but not limited to for reasons of compliance with applicable laws, requests by Government agencies, and court orders.
(c) any changes made to the Website;
(d) temporary or permanent cessation of the Website, the Services, Divine Wisdom ’s business or any part thereof;
(e) any unauthorized access to or alteration of the User transmissions or data, if any;
(f) statements or conduct of any third-party on the Website; and
(g) any fraud, security breach, misconduct or negligence by any third parties and/or advertisers and/or service providers.

10.10 Divine Wisdom does not warrant that access and use of its Website and/or its content and/or Service will be uninterrupted, timely, secure and error-free since the same could be affected by overload/breakdown of receiving network, servers or applications; system failures; and frauds out of Divine Wisdom ’s control. Divine Wisdom shall not be liable for any loss or damage whether financial or otherwise caused by a distributed denial-of-service attack, viruses or other technologically harmful material that may infect the User’s device, programs, data or other proprietary material due to use of the

10.11 The User shall verify the veracity of all the information, opinions, views, and advice on your own before undertaking reliance and acting thereupon. The User expressly agrees and understands that the Services, materials, consultations, content and information offered on the Website is not a substitute for professional advice and Divine Wisdom disclaims all liability whether financial or otherwise for any claims arising thereto.

10.12 Divine Wisdom is not responsible for the availability or content of any third-party material you access through the Divine Wisdom does not endorse and is not responsible or liable for any content, advertising, products, services or information of or relating to a third-party (including payment for and delivery of such products or services). Divine Wisdom shall not be responsible for any damage, loss or offence caused by or, in connection with, any content, material, advertising, products, services or information of any third-party that may be available on the Website. Any terms, conditions, warranties or representations associated with such dealings, are solely between the User and the relevant provider of the service and the User agrees to indemnify Divine Wisdom for any claims arising thereto.

10.13 Divine Wisdom shall not be responsible and/or liable whether financially or otherwise in any manner whatsoever for any third-party action which results in the information provided by the User being exposed and/or misused by such third-party who accessed such information without any authorization from Divine Wisdom.

10.14 Divine Wisdom may use a third-party as a payment By subscribing to Divine Wisdom ’s Services, the User expressly authorizes a third-party payment gateway to charge the User’s credit card/debit card and/or bank account. Divine Wisdom disclaims any and all liability accruing to the User as a result of any fraud, misuse and/or duplicate transactions arising thereto.

10.15 Divine Wisdom neither warrants nor represents that use of the Services by the User will not infringe the rights of third parties not owned by or affiliated with Divine Wisdom.

10.16 There may be delay in provision of Services due to factors beyond the reasonable control of Divine Wisdom and therefore Divine Wisdom shall not be held responsible and liable for any delay and/or failure in performance of Services by Divine Wisdom due to such fa The Website may be subject to changes and/or improvements periodically. During the process of up-gradation, repair, maintenance and/or improvements, contents/systems/programs/software may be suspended for any use. Divine Wisdom shall not be liable for any inconvenience, loss, damage, cost, expenses which may be incurred by the User due to unavailability of the Website for any use. Divine Wisdom does not warrant that the software will work on all networks and/or will be available in all geographical areas.

11. Personal, Non-Commercial and Non-Assignable Use

By registering on the Website, the User confirms that use of the Website shall be for his/her personal and/or non-commercial purpose (as may be applicable). The User confirms that the User’s right to access, use, deal with or transact at the Website cannot be assigned to any other person and custody of the User ID and password to access, deal with or transact at the Website shall be the sole responsibility of the User and the User shall be responsible and liable for any misuse of the User ID and password assigned to the User by Divine Wisdom.

12. Links to other Websites

The Website may contain hyperlinks to Websites operated by persons other than Divine Wisdom (hereinafter referred to as the “Web Links”). Such Web Links are provided for the User’s reference and convenience only and they do not constitute as any recommendation and/or advice and should not be relied upon in making and/or refraining from making any decision. Divine Wisdom reserves its right to remove any such Web Links anytime without any prior notice. Divine Wisdom is not under obligation to review the contents of Web Links and therefore does not control the contents of those Web Links. The User leaves the Website by clicking on Web Links and goes to respective internet Websites and use of those Web Links shall be regulated by terms provided on respective Websites. Divine Wisdom is neither acting as publisher of contents of those Web Links nor endorser of any representation published on those Web Links. The User confirms that any access of Web Links by the User shall be entirely at the User’s own risk.

13. Description and Fees

Divine Wisdom shall endeavour to the extent possible to be as accurate as possible while providing Service descriptions and fees. However, Divine Wisdom does not warrant that descriptions and/or other content and/or fees related to the Services and/or other information and content contained in this Website is accurate, complete, reliable, current and error-free.

14. Promotional Material

Divine Wisdom shall be entitled to send and the User hereby gives consent to receive, information / offers / promotional mails and messages pertaining to the Services offered by Divine Wisdom and associate organisations from time to time.

In case the User wishes to de-activate any promotional material being provided to the User, the User shall notify Divine Wisdom at mails@eightspiritualbreaths.com

15. Indemnity and Limitation of Liability

Without prejudice to the rights of Divine Wisdom  under law, in equity and/or under this Agreement, the User agrees to protect, hold harmless and indemnify Divine Wisdom , the Instructor, its employees, representatives, agents, to the fullest extent, at all times, from and against any and all claims, demands, damages, obligations, losses, liabilities, judgments, settlements, costs and expenses (including reasonable attorneys’ fees and costs) arising from or relating to: (i) the User’s access, use or misuse of the Website; and/or (ii) the User’s breach or alleged breach of this Agreement and/or breach of the User’s representations, warranties, guarantees, covenants, obligations and undertakings; and/or (iii) any violation by the User of any applicable laws; and/or (iv) any violation by the User of Divine Wisdom ’s rights and/or the rights of third parties, including without limitation, infringement of copyright, trademark, service mark, patent, trade secret, privacy or other intellectual property or proprietary right or misappropriation of any property.

Subject to applicable laws, Divine Wisdom  shall not be liable for any indirect, incidental, special, consequential, or punitive damages, or any loss of profits or revenues, whether incurred directly or indirectly, or any loss of data, use, goodwill, or other intangible losses, resulting from: (a) your access to or use of or inability to access or use the Services; (b) any conduct or content of any party other than Divine Wisdom , including without limitation, any defamatory, offensive, or illegal conduct; or (c) unauthorized access, use, or alteration of your content or information. It is expressly provided that the maximum liability of Divine Wisdom for any reasons whatsoever shall not exceed the total amount of fees received by Divine Wisdom from the User for the use of the applicable Digital Content.

The User acknowledges and agrees that the disclaimers and the limitations of liability set forth in this Agreement are reasonable and fair and that these limitations are the basis on which Divine Wisdom is making the Services available to the User. The User further acknowledge and agree that any cause of action related to the Services must commence within 1 (one) year after the cause of action accrues otherwise, such cause of action shall not be permissible, subject to applicable laws.

16. Termination

16.1 Divine Wisdom may, at any time, terminate or suspend any and all Services and/or access to the Website immediately, without prior notice and/or liability under the following circumstances:

(a) The User breaches any of the terms or conditions of this Agreement and/or other incorporated agreements and/or guidelines.
(b) Requests by law enforcement and/or other government agencies.
(c) Discontinuance and/or material modification to the Website and/or Service (or any part thereof).
(d) Unexpected technical and/or security issues and/or problem
(e) Engagement by the User in fraudulent and/or illegal activities and/or suspected impersonation and/or due to result of any background search and/or credit check conducted on the User and/or any breach or threatened breach/ infringement of intellectual property rights of Divine Wisdom.
(f) Non – payment of Subscription Fees owed by the User in connection with the use of Website and/or Ser

16.2 Termination of the User account includes:

(a) Removal of access to all offerings within the Service and the Website.
(b) Deletion of the User ID and password and all related information, files and content associated with or inside the User account (or any part thereof).
(c) Barring of further use of the Website and/or Service.

16.3 The User hereby agrees that all terminations for cause shall be made in Divine Wisdom ’s sole discretion and that Divine Wisdom shall not be liable to the User or any third-party for any termination of the User account, any associated email address, or access to the Ser Any Subscription Fees paid hereunder are non-refundable. All provisions of this Agreement which by their nature should survive termination shall survive termination, including, without limitation, ownership provisions and warranty disclaimers.

17. Governing Law

This Agreement shall be governed by, construed interpreted, and enforced in accordance with the laws of India. Except for injunctive reliefs, specific performance and damages any other disputes arising in respect hereto shall be subject to exclusive jurisdiction of the Courts of Mumbai, Maharashtra.

18. General Provisions

18.1 No Partnership

None of the provisions of this Agreement shall be deemed to constitute a partnership or agency between the User and Divine Wisdom and the User shall have no authority to bind Divine Wisdom in any manner whatsoever.

18.2 Electronic communication

The User consents and gives his/her consent to receive communications from Divine Wisdom electronically/through electronic records. Divine Wisdom will communicate with the User by e-mail and/or by posting notices on this Website. The User agrees that all agreements, notices, disclosures and other communications that Divine Wisdom provides to the User electronically satisfy all legal requirement of adequate service of notice/electronic record. This document is an electronic record in terms of Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical and/or digital signatures.

18.3 Assignment

Divine Wisdom can assign its rights and/or obligations provided herein or arising out of this Agreement to any person. The User cannot assign its rights and remedies and/or transfer its obligations under this Agreement without prior written consent of Divine Wisdom.

18.4 Severability

Should any provision of this Agreement be determined to be unenforceable and/or invalid, or any transaction contemplated hereby determined to be unlawful by any court of law, or competent government body for any reason, all other provisions shall continue (except if this Agreement stands terminated) in full force and effect.

18.5 Grievances

In case of any queries and/or grievances and/or assistance required, if any, the User shall write to the grievance email id as set out below.

Grievance Officer

Email Address: admin@discoverwhoami.com

On receipt of any concerns or complaints the Grievance Officer, the Grievance Officer shall acknowledge the receipt of the concern or complaint within 24 (twenty-four) hours and will employ all commercially reasonable efforts to address the same at the earliest but no later than fifteen (15) days of receipt of same.
`

const HIGHLIGHT_TERMS = [
  'Terms & Conditions and User Agreement for transacting at and/or dealing with the Website',
  'Recitals',
  'IT Intermediary Rules',
  'The Who Am I Course',
  'Website',
  'Divine Wisdom',
  'Instructor',
  'Digital Content',
  'Subscription Fees',
  'Services',
  'Acceptance',
  'User',
  'Third Party Content',
  'User Content',
  'Intellectual Property',
  'Grievance Officer'
]

function highlightText(input: string) {
  return HIGHLIGHT_TERMS.reduce(
    (current, term) => current.replaceAll(term, `<strong>${term}</strong>`),
    input
  )
}

const PARAGRAPHS = TERMS_TEXT.split('\n\n').filter(Boolean)

export const metadata = { title: 'Terms & Conditions - Discover Who Am I' }

export default function TermsPage() {
  const palette = themeLibrary[TERMS_THEME].classes
  const headingClass = palette.card.title

  return (
    <div className="space-y-8">
      <section className="rounded-3xl border border-sky-100 bg-white/95 p-8 text-center shadow-sm">
        <p className="text-xs font-semibold uppercase tracking-[0.4em] text-sky-400">Legal</p>
        <h1 className={`mt-2 text-3xl font-semibold tracking-tight ${headingClass}`}>Terms & Conditions</h1>
        <a
          href="https://discoverwhoami.com/"
          className="mt-3 inline-block text-lg font-semibold text-sky-600 underline decoration-sky-400 hover:text-sky-700"
        >
          https://discoverwhoami.com/
        </a>
        <p className={`mt-2 text-base leading-7 ${palette.muted}`}>
          Terms &amp; Conditions and User Agreement for transacting at and/or dealing with the Website{' '}
          <a href="https://discoverwhoami.com/" className="font-semibold text-sky-600 underline decoration-sky-400">
            https://discoverwhoami.com/
          </a>{' '}
          at <span className="font-semibold">Divine Wisdom</span>
        </p>
      </section>
      <section className="rounded-3xl border border-sky-100 bg-white/95 p-8 text-base leading-7 text-sky-800 shadow-sm">
        <div className="space-y-4">
          {PARAGRAPHS.map((paragraph, index) => (
            // eslint-disable-next-line react/no-danger
            <p key={index} dangerouslySetInnerHTML={{ __html: highlightText(paragraph) }} />
          ))}
        </div>
      </section>
    </div>
  )
}
